WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)

SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900

GRID_WIDTH = 10
GRID_HEIGHT = 10

SCALE = 1
CELL_SIZE = 60 * SCALE

BUTTON_FONT_SIZE = 30
BUTTON_FONT_TYPE = 'Impact'
LOGGER_FONT_SIZE = 12
LOGGER_FONT_TYPE = 'Arial'
CHOOSE_MENU_SIZE = 19
CHOOSE_MENU_TYPE = 'dejavusans'

LOGS_SPACE = 0  # space between lines in logger
CHOOSE_MENU_SPACE = 0

BG_COLOR = WHITE
CELL_BORDER_COLOR = RED
BOARD_COLOR = WHITE
BUTTON_COLOR = GREEN
BUTTON_HOVER_COLOR = RED
BUTTON_TEXT_COLOR = BLACK
LOGGER_TEXT_COLOR = BLACK
CHOOSE_MENU_COLOR = YELLOW
CHOOSE_MENU_TEXT_COLOR = BLACK

# X and Y coordinates are the top left coordinates of rectangles
BOARD_X = 350
BOARD_Y = 200
BUTTON_WIDTH = 300
BUTTON_HEIGHT = 100
LOAD_BUTTON_X = 10
LOAD_BUTTON_Y = SCREEN_HEIGHT - BUTTON_HEIGHT - 50
SAVE_BUTTON_X = 10
SAVE_BUTTON_Y = LOAD_BUTTON_Y - BUTTON_HEIGHT - 50
LOGS_X = 5
LOGS_Y = 5
CHOOSE_MENU_HEIGHT = 300
CHOOSE_MENU_WIDTH = 400
CHOOSE_MENU_X = SCREEN_WIDTH - CHOOSE_MENU_WIDTH - 10
CHOOSE_MENU_Y = SCREEN_HEIGHT - CHOOSE_MENU_HEIGHT - 10
